name = "BarycentricInterpolation"
uuid = "e9d15388-4623-4d1e-9e26-4fb9a6fc2205"
authors = ["David AW Barton <david.barton@bristol.ac.uk>"]
version = "0.1.1"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "LinearAlgebra"]
